version: 0.0
os: linux
files:
  - source: /dist/
    destination: /home/ubuntu/s3manager
hooks:
  BeforeInstall:
    - location: Scripts/before_install.sh
    - timeout: 180
    - runas: root
  AfterInstall:
    - location: Scripts/after_install.sh
      timeout: 180
      - runas: root
  ApplicationStart:
    - location: Scripts/app_start.sh
      timeout: 3600
      - runas: root