version: 0.0
os: linux
files:
  - source: dist/overcruxweb
    destination: /home/ubuntu/s3manager
hooks:
  BeforeInstall:
    - location: Script/before_install.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: Script/after_install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: Script/app_start.sh
      timeout: 3600
      runas: root