version: 0.2
phases:
  pre_build:
    commands:
      - echo Instalando dependencias
      - sudo apt install npm
      - sudo npm install @angular/cli@11.0.0 -g > /dev/null
  build:
    commands:
      - echo Build iniciado em `date`
      - sudo npm run build
  post_build:
    commands:
      - echo Build finalizado em `date`	
artifacts:
  files:
    - dist/**/*
    - Script/*
    - appspec.yml    
 